services:
    # backend:
    #     build:
    #       context: .
    #       dockerfile: Dockerfile
    #     ports:
    #       - "5000:5000"
    #     depends_on:
    #       - psql
    #     networks:
    #       - psql-network
    psql:
        image: postgres:latest
        environment:
            POSTGRES_DB: voicerecdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        # expose:
        #   - "5432"
        ports:
          - "5433:5432"
        volumes:
          - db_data:/var/lib/postgresql/data
        networks:
          - psql-network

networks:
    psql-network:
        name: psql-network
        driver: bridge

volumes:
    db_data:
        driver: local